"""Session-scoped, process-memory workspace store.

There is intentionally no database in this module.  The browser sends a random
``X-TestPilot-Session`` ID with each request, and this module keeps that
workspace only in Python memory until the browser refreshes or leaves the page.
"""
from __future__ import annotations

import copy
import time
from contextvars import ContextVar, Token
from dataclasses import dataclass, field
from threading import RLock
from typing import Any

DB_PATH = "session-scoped process-memory store (no SQL)"
_DEFAULT_SESSION_ID = "anonymous"
_active_session_id: ContextVar[str] = ContextVar("testpilot_session_id", default=_DEFAULT_SESSION_ID)
_lock = RLock()
_discarded_sessions: set[str] = set()


@dataclass
class _SessionStore:
    projects: dict[str, dict] = field(default_factory=dict)
    jobs: dict[str, dict] = field(default_factory=dict)
    runs: dict[str, dict] = field(default_factory=dict)
    testcases: dict[int, dict] = field(default_factory=dict)
    next_record_id: int = 1


_sessions: dict[str, _SessionStore] = {}


def _normalize_session_id(value: str | None) -> str:
    session_id = str(value or "").strip()
    return session_id[:128] if session_id else _DEFAULT_SESSION_ID


def _session_store(*, create: bool = True) -> _SessionStore | None:
    session_id = _active_session_id.get()
    with _lock:
        if session_id in _discarded_sessions:
            return None
        if create:
            return _sessions.setdefault(session_id, _SessionStore())
        return _sessions.get(session_id)


def _clone(value: Any) -> Any:
    return copy.deepcopy(value)


def activate_session(session_id: str | None) -> Token:
    """Select the transient workspace attached to the current web session."""
    normalized = _normalize_session_id(session_id)
    token = _active_session_id.set(normalized)
    # IDs are generated by the browser and are never reused after a refresh.
    # Removing a stale tombstone makes a newly issued ID usable in the vanishingly
    # unlikely event it happens to equal an old one.
    with _lock:
        _discarded_sessions.discard(normalized)
        _sessions.setdefault(normalized, _SessionStore())
    return token


def reset_session(token: Token) -> None:
    _active_session_id.reset(token)


def discard_session(session_id: str | None) -> None:
    """Forget every project, job, run and testcase for a browser session."""
    normalized = _normalize_session_id(session_id)
    if normalized == _DEFAULT_SESSION_ID:
        return
    with _lock:
        _sessions.pop(normalized, None)
        _discarded_sessions.add(normalized)


def init_db() -> None:
    """Compatibility hook kept for the FastAPI middleware; it creates no DB."""
    _session_store()


def _normalize_project(project: dict) -> dict:
    project_id = str(project.get("id") or project.get("project_id") or "").strip()
    if not project_id:
        raise ValueError("project id is required")
    now = time.time()
    project_type = str(project.get("type") or project.get("project_type") or "both").strip().lower()
    if project_type not in {"web", "api", "both"}:
        project_type = "both"
    payload = _clone(project)
    payload.update({
        "id": project_id,
        "name": str(project.get("name") or project_id).strip(),
        "description": str(project.get("description") or "").strip(),
        "type": project_type,
        "createdAt": float(project.get("createdAt") or project.get("created_at") or now),
        "updatedAt": float(project.get("updatedAt") or project.get("updated_at") or now),
    })
    return payload


def upsert_project(project: dict) -> dict:
    payload = _normalize_project(project)
    store = _session_store()
    if store is None:
        return payload
    with _lock:
        previous = store.projects.get(payload["id"])
        if previous:
            payload["createdAt"] = previous.get("createdAt", payload["createdAt"])
        store.projects[payload["id"]] = _clone(payload)
    return _clone(payload)


def get_project(project_id: str) -> dict | None:
    store = _session_store(create=False)
    if not store:
        return None
    with _lock:
        project = store.projects.get(project_id)
        return _clone(project) if project else None


def list_projects() -> list[dict]:
    store = _session_store(create=False)
    if not store:
        return []
    with _lock:
        return [_clone(project) for project in sorted(
            store.projects.values(),
            key=lambda item: (float(item.get("updatedAt") or 0), float(item.get("createdAt") or 0)),
            reverse=True,
        )]


def delete_project(project_id: str) -> bool:
    store = _session_store(create=False)
    if not store:
        return False
    with _lock:
        if project_id not in store.projects:
            return False
        del store.projects[project_id]
        store.testcases = {key: value for key, value in store.testcases.items() if value["projectId"] != project_id}
        store.runs = {key: value for key, value in store.runs.items() if value["project_id"] != project_id}
        return True


def create_analysis_job(*, job_id: str, kind: str, project_id: str, folder_id: str, source_names: list[str]) -> None:
    store = _session_store()
    if store is None:
        return
    now = time.time()
    with _lock:
        store.jobs[job_id] = {
            "job_id": job_id, "kind": kind, "project_id": project_id, "folder_id": folder_id,
            "status": "queued", "stage": "queued", "message": "Đã tiếp nhận tài liệu. Đang xếp hàng phân tích.",
            "progress": 0, "run_id": None, "source_names": _clone(source_names), "error": {},
            "created_at": now, "updated_at": now,
        }


def update_analysis_job(job_id: str, *, status: str | None = None, stage: str | None = None,
                        message: str | None = None, progress: int | None = None,
                        run_id: str | None = None, error_payload: dict | None = None) -> None:
    store = _session_store(create=False)
    if not store:
        return
    with _lock:
        job = store.jobs.get(job_id)
        if not job:
            return
        if status is not None:
            job["status"] = status
        if stage is not None:
            job["stage"] = stage
        if message is not None:
            job["message"] = message
        if progress is not None:
            job["progress"] = max(0, min(100, int(progress)))
        if run_id is not None:
            job["run_id"] = run_id
        if error_payload is not None:
            job["error"] = _clone(error_payload)
        job["updated_at"] = time.time()


def get_analysis_job(job_id: str) -> dict | None:
    store = _session_store(create=False)
    if not store:
        return None
    with _lock:
        job = store.jobs.get(job_id)
        return _clone(job) if job else None


def fail_orphaned_analysis_jobs() -> int:
    # Memory is intentionally empty after a process restart, so no job can survive it.
    return 0


def save_run(*, run_id: str, kind: str, project_id: str, folder_id: str,
             source_names: list[str], matrix: dict, agent1_summary: dict) -> None:
    store = _session_store()
    if store is None:
        return
    with _lock:
        store.runs[run_id] = {
            "run_id": run_id, "kind": kind, "project_id": project_id, "folder_id": folder_id,
            "created_at": time.time(), "source_names": _clone(source_names), "matrix": _clone(matrix),
            "agent1_summary": _clone(agent1_summary),
        }


_TC_DEFAULTS = {
    "preCondition": "", "importance": "", "steps": [], "testData": "", "expectedResult": "",
    "actualResult": "", "run1": "", "run2": "", "run3": "", "currentResult": "", "note": "",
    "errorCode": "", "qcWriter": "", "sprintWriter": "", "qcExecutor": "", "sprintExecutor": "",
    "reviewer": "", "reviewDate": "", "reviewContent": "", "needAuto": "", "automated": "",
    "smoke": "", "regression": "", "outdated": "", "outdatedDate": "", "type": "Chức năng",
    "sourceRuleId": "", "sourceRequirement": "", "featureGroup": "", "featureName": "", "category": "",
    "screen": "", "validation": {},
}


def _new_testcase(*, record_id: int, run_id: str, project_id: str, folder_id: str, scope: str,
                  sort_order: int, payload: dict) -> dict:
    now = time.time()
    result = _clone(_TC_DEFAULTS)
    result.update(_clone(payload))
    result.update({
        "recordId": record_id, "runId": run_id, "projectId": project_id, "folderId": folder_id,
        "scope": scope, "sortOrder": int(sort_order), "id": str(result.get("id") or ""),
        "name": str(result.get("name") or ""), "createdAt": now, "updatedAt": now,
    })
    return result


def _folder_cases(store: _SessionStore, project_id: str, folder_id: str, scope: str) -> list[dict]:
    return sorted(
        (case for case in store.testcases.values()
         if case["projectId"] == project_id and case["folderId"] == folder_id and case["scope"] == scope),
        key=lambda case: (int(case.get("sortOrder") or 0), int(case["recordId"])),
    )


def _renumber_folder(store: _SessionStore, project_id: str, folder_id: str, scope: str) -> None:
    for index, case in enumerate(_folder_cases(store, project_id, folder_id, scope), start=1):
        case["sortOrder"] = index - 1
        case["id"] = f"TC_{index:03d}"
        case["updatedAt"] = time.time()


def replace_run_testcases(*, run_id: str, project_id: str, folder_id: str, scope: str,
                          testcases: list[dict]) -> list[dict]:
    store = _session_store()
    if store is None:
        return []
    with _lock:
        for record_id in [key for key, case in store.testcases.items()
                          if case["projectId"] == project_id and case["folderId"] == folder_id and case["scope"] == scope]:
            del store.testcases[record_id]
        for index, testcase in enumerate(testcases):
            record_id = store.next_record_id
            store.next_record_id += 1
            store.testcases[record_id] = _new_testcase(
                record_id=record_id, run_id=run_id, project_id=project_id, folder_id=folder_id,
                scope=scope, sort_order=index, payload=testcase,
            )
        _renumber_folder(store, project_id, folder_id, scope)
        return [_clone(case) for case in _folder_cases(store, project_id, folder_id, scope) if case["runId"] == run_id]


def get_run(run_id: str) -> dict | None:
    store = _session_store(create=False)
    if not store:
        return None
    with _lock:
        run = store.runs.get(run_id)
        return _clone(run) if run else None


def list_run_testcases(run_id: str) -> list[dict]:
    store = _session_store(create=False)
    if not store:
        return []
    with _lock:
        return [_clone(case) for case in sorted(
            (item for item in store.testcases.values() if item["runId"] == run_id),
            key=lambda case: (int(case.get("sortOrder") or 0), int(case["recordId"])),
        )]


def list_folder_testcases(project_id: str, folder_id: str, scope: str) -> list[dict]:
    store = _session_store(create=False)
    if not store:
        return []
    with _lock:
        return [_clone(case) for case in _folder_cases(store, project_id, folder_id, scope)]


def list_project_tree_summary(project_id: str) -> list[dict]:
    store = _session_store(create=False)
    if not store:
        return []
    with _lock:
        grouped: dict[tuple[str, str, str], int] = {}
        for case in store.testcases.values():
            if case["projectId"] != project_id:
                continue
            key = (case["scope"], str(case.get("screen") or ""), case["folderId"])
            grouped[key] = grouped.get(key, 0) + 1
        return [
            {"scope": scope, "screen": screen, "folder_id": folder_id, "count": count}
            for (scope, screen, folder_id), count in sorted(grouped.items(), key=lambda item: item[0])
        ]


def list_project_testcases(project_id: str, scope: str | None = None) -> list[dict]:
    store = _session_store(create=False)
    if not store:
        return []
    with _lock:
        cases = [case for case in store.testcases.values()
                 if case["projectId"] == project_id and (scope is None or case["scope"] == scope)]
        cases.sort(key=lambda case: (
            case["scope"], str(case.get("screen") or "").casefold(), case["folderId"],
            int(case.get("sortOrder") or 0), int(case["recordId"]),
        ))
        return [_clone(case) for case in cases]


def _latest_run(predicate) -> dict | None:
    store = _session_store(create=False)
    if not store:
        return None
    with _lock:
        candidates = [run for run in store.runs.values() if predicate(run)]
        return _clone(max(candidates, key=lambda run: float(run["created_at"]))) if candidates else None


def get_latest_run_for_folder(project_id: str, folder_id: str, scope: str) -> dict | None:
    return _latest_run(lambda run: run["project_id"] == project_id and run["folder_id"] == folder_id and run["kind"] == scope)


def get_latest_run_for_project_scope(project_id: str, scope: str) -> dict | None:
    return _latest_run(lambda run: run["project_id"] == project_id and run["kind"] == scope)


def renumber_folder_testcase_ids(project_id: str, folder_id: str, scope: str) -> None:
    store = _session_store(create=False)
    if store:
        with _lock:
            _renumber_folder(store, project_id, folder_id, scope)


def renumber_all_testcase_ids() -> None:
    store = _session_store(create=False)
    if not store:
        return
    with _lock:
        groups = {(case["projectId"], case["folderId"], case["scope"]) for case in store.testcases.values()}
        for project_id, folder_id, scope in groups:
            _renumber_folder(store, project_id, folder_id, scope)


_EDITABLE_TESTCASE_FIELDS = frozenset(_TC_DEFAULTS) | {"name", "sortOrder"}


def update_testcase(record_id: int, payload: dict) -> dict | None:
    store = _session_store(create=False)
    if not store:
        return None
    with _lock:
        item = store.testcases.get(record_id)
        if not item:
            return None
        for key in _EDITABLE_TESTCASE_FIELDS:
            if key in payload:
                item[key] = _clone(payload[key])
        item["updatedAt"] = time.time()
        _renumber_folder(store, item["projectId"], item["folderId"], item["scope"])
        return _clone(item)


def get_testcase(record_id: int) -> dict | None:
    store = _session_store(create=False)
    if not store:
        return None
    with _lock:
        item = store.testcases.get(record_id)
        return _clone(item) if item else None


def create_testcase(*, project_id: str, folder_id: str, scope: str, run_id: str, payload: dict) -> dict:
    store = _session_store()
    if store is None:
        raise RuntimeError("Browser session has ended")
    with _lock:
        record_id = store.next_record_id
        store.next_record_id += 1
        item = _new_testcase(
            record_id=record_id, run_id=run_id, project_id=project_id, folder_id=folder_id,
            scope=scope, sort_order=len(_folder_cases(store, project_id, folder_id, scope)), payload=payload,
        )
        store.testcases[record_id] = item
        _renumber_folder(store, project_id, folder_id, scope)
        return _clone(item)


def delete_testcase(record_id: int) -> bool:
    store = _session_store(create=False)
    if not store:
        return False
    with _lock:
        item = store.testcases.pop(record_id, None)
        if not item:
            return False
        _renumber_folder(store, item["projectId"], item["folderId"], item["scope"])
        return True
